files:
  - url: ""
    time: 1623476280663.yml
    name: config.yaml
    selected: []
  - time: 1678978122562.yml
    name: é­”æˆ’.net
    url: https://mojie.best/api/v1/client/subscribe?token=387e9a0fdb4596a23cfd34836f2c9aa3
    selected:
      - name: GLOBAL
        now: å‰©ä½™æµé‡ï¼š66.24 GB
      - name: èŠ‚ç‚¹é€‰æ‹©
        now: æ•…éšœè½¬ç§»
      - name: ChatGPT
        now: èŠ‚ç‚¹é€‰æ‹©
      - name: ä¸­è½¬èŠ‚ç‚¹
        now: æ—¥æœ¬-ä¼˜åŒ–
      - name: ç›´è¿èŠ‚ç‚¹
        now: è‘¡è„ç‰™PT-T
      - name: Netflix
        now: DIRECT
      - name: ç£åŠ›ä¸‹è½½
        now: DIRECT
      - name: å“”å“©å“”å“©
        now: æ—¥æœ¬-ä¼˜åŒ–3
      - name: è°·æ­ŒæœåŠ¡
        now: èŠ‚ç‚¹é€‰æ‹©
      - name: Twitter
        now: èŠ‚ç‚¹é€‰æ‹©
      - name: å¾®è½¯æœåŠ¡
        now: èŠ‚ç‚¹é€‰æ‹©
      - name: è‹¹æœæœåŠ¡
        now: DIRECT
      - name: Steam
        now: èŠ‚ç‚¹é€‰æ‹©
      - name: æ¼ç½‘ä¹‹é±¼
        now: èŠ‚ç‚¹é€‰æ‹©
    interval: 24
    subInfo:
      upload: 10190434749
      download: 58269620123
      total: 139586437120
    mode: global
    cron: ""
    headers: ""
  - time: 1679016360220.yml
    name: ä¸€å…ƒæœºåœº
    url: https://sub1.smallstrawberry.com/api/v1/client/subscribe?token=7790dcf036e4af9cbc6724cf3ee5b63b
    selected:
      - name: GLOBAL
        now: DIRECT
      - name: ä¸€å…ƒæœºåœº
        now: ğŸ‡­ğŸ‡°é¦™æ¸¯ 02 | ä¸“çº¿
    interval: 24
    subInfo:
      upload: 756434992
      download: 863176023
      total: 536870912000
      expire: 1709083579
    mode: rule
index: 1
